Repository wp-cli/core-command, pull requests merged in 2018-12, with the labels that each got.

#93 Use "installation" instead of "install"
  src/Core_Command.php
Labels: scope:testing

#100 Fix tests for uncached nightly downloads
  features/core-update.feature
Labels: bug, scope:testing

#101 Adapt framework requirement
  composer.json
Labels: scope:distribution
