Repository wp-cli/core-command, pull requests merged in 2019-04, with the labels that each got.

#107 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
  features/core-update.feature
Labels: scope:distribution

#115 Replace instances of `wp.dev` with `example.com`
  README.md
  features/core.feature
  src/Core_Command.php
Labels: scope:documentation

#117 Implement CS checking based on the `WP_CLI_CS` ruleset
  .distignore
  .gitignore
  composer.json
  core-command.php
  phpcs.xml.dist
  src/Core_Command.php
  src/WP_CLI/Core/CoreUpgrader.php
  src/WP_CLI/Core/NonDestructiveCoreUpgrader.php
Labels: command:core

#120 Change `CoreUpgrader::download_package` signature
  src/WP_CLI/Core/CoreUpgrader.php
Labels: command:core-update

#111 Enhancement: Add PHP 7.3 to Travis CI build matrix
  .travis.yml
  features/core-update.feature
Labels: scope:testing

#121 Lock framework version to ^2.2
  composer.json
Labels: scope:distribution
